/*
 * THIS FILE IS AUTOMATICALLY GENERATED
 *
 * I2C-Generator: 0.3.0
 * Yaml Version: 1.1.0
 * Template Version: 0.7.0-80-gf4d3b1b
 */
/*
 * Copyright (c) 2021, Sensirion AG
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * * Redistributions of source code must retain the above copyright notice, this
 *   list of conditions and the following disclaimer.
 *
 * * Redistributions in binary form must reproduce the above copyright notice,
 *   this list of conditions and the following disclaimer in the documentation
 *   and/or other materials provided with the distribution.
 *
 * * Neither the name of Sensirion AG nor the names of its
 *   contributors may be used to endorse or promote products derived from
 *   this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include "sfm_sf06_i2c.h"
#include "sensirion_common.h"
#include "sensirion_i2c.h"
#include "sensirion_i2c_hal.h"

#define SFM_SF06_I2C_ADDRESS _driver.i2c_address

static sfm_sf06_t _driver = {.flow_offset = 0,
                             .flow_scaling_factor = 1,
                             .i2c_address = 0,
                             .flow_unit = 0};

const sfm_sf06_t* init_driver(uint8_t i2c_address) {
    _driver.i2c_address = i2c_address;
    return &_driver;
}

int16_t sfm_sf06_start_o2_continuous_measurement(void) {
    int16_t error;
    uint8_t buffer[2];
    uint16_t offset = 0;

    error = sfm_sf06_read_scale_offset_unit(
        cmd_02_measurement, &_driver.flow_scaling_factor, &_driver.flow_offset,
        &_driver.flow_unit);
    if (error) {
        return error;
    }

    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x3603);
    error = sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_usec(12000);
    return NO_ERROR;
}

int16_t sfm_sf06_start_air_continuous_measurement(void) {
    uint8_t buffer[2];
    uint16_t offset = 0;

    int16_t error = sfm_sf06_read_scale_offset_unit(
        cmd_air_measurement, &_driver.flow_scaling_factor, &_driver.flow_offset,
        &_driver.flow_unit);
    if (error) {
        return error;
    }

    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x3608);

    return sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
}

int16_t sfm_sf06_start_n2o_continuous_measurement(void) {
    int16_t error;
    uint8_t buffer[2];
    uint16_t offset = 0;

    error = sfm_sf06_read_scale_offset_unit(
        cmd_no2_measurement, &_driver.flow_scaling_factor, &_driver.flow_offset,
        &_driver.flow_unit);
    if (error) {
        return error;
    }

    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x3615);
    error = sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_usec(12000);
    return NO_ERROR;
}

int16_t sfm_sf06_start_co2_continuous_measurement(void) {
    int16_t error;
    uint8_t buffer[2];
    uint16_t offset = 0;

    error = sfm_sf06_read_scale_offset_unit(
        cmd_co2_measurement, &_driver.flow_scaling_factor, &_driver.flow_offset,
        &_driver.flow_unit);
    if (error) {
        return error;
    }

    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x361E);

    error = sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_usec(12000);
    return NO_ERROR;
}

int16_t sfm_sf06_start_air_o2_continuous_measurement(uint16_t volume_fraction) {
    int16_t error;
    uint8_t buffer[5];
    uint16_t offset = 0;

    error = sfm_sf06_read_scale_offset_unit(
        cmd_airo2_measurement, &_driver.flow_scaling_factor,
        &_driver.flow_offset, &_driver.flow_unit);
    if (error) {
        return error;
    }

    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x3632);

    offset = sensirion_i2c_add_uint16_t_to_buffer(&buffer[0], offset,
                                                  volume_fraction);

    error = sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_usec(12000);
    return NO_ERROR;
}

int16_t sfm_sf06_start_no2_o2_continuous_measurement(uint16_t volume_fraction) {
    int16_t error;
    uint8_t buffer[5];
    uint16_t offset = 0;

    error = sfm_sf06_read_scale_offset_unit(
        cmd_no2o2_measurement, &_driver.flow_scaling_factor,
        &_driver.flow_offset, &_driver.flow_unit);
    if (error) {
        return error;
    }

    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x3639);

    offset = sensirion_i2c_add_uint16_t_to_buffer(&buffer[0], offset,
                                                  volume_fraction);

    error = sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_usec(12000);
    return NO_ERROR;
}

int16_t sfm_sf06_start_c02_02_continuous_measurement(uint16_t volume_fraction) {
    int16_t error;
    uint8_t buffer[5];
    uint16_t offset = 0;

    error = sfm_sf06_read_scale_offset_unit(
        cmd_co2o2_measurement, &_driver.flow_scaling_factor,
        &_driver.flow_offset, &_driver.flow_unit);
    if (error) {
        return error;
    }

    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x3646);

    offset = sensirion_i2c_add_uint16_t_to_buffer(&buffer[0], offset,
                                                  volume_fraction);

    error = sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
    if (error) {
        return error;
    }
    sensirion_i2c_hal_sleep_usec(12000);
    return NO_ERROR;
}

int16_t sfm_sf06_read_measurement_data(int16_t* flow, int16_t* temperature,
                                       uint16_t* status_word) {
    int16_t error;
    uint8_t buffer[9];

    error =
        sensirion_i2c_read_data_inplace(SFM_SF06_I2C_ADDRESS, &buffer[0], 6);
    if (error) {
        return error;
    }
    *flow = sensirion_common_bytes_to_int16_t(&buffer[0]);
    *temperature = sensirion_common_bytes_to_int16_t(&buffer[2]);
    *status_word = sensirion_common_bytes_to_uint16_t(&buffer[4]);
    return NO_ERROR;
}

int16_t sfm_sf06_update_concentration_set(uint16_t volume_fraction) {
    uint8_t buffer[5];
    uint16_t offset = 0;
    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0xE17D);

    offset = sensirion_i2c_add_uint16_t_to_buffer(&buffer[0], offset,
                                                  volume_fraction);

    return sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
}

int16_t sfm_sf06_update_concentration_activate(void) {
    uint8_t buffer[2];
    uint16_t offset = 0;
    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0xE000);

    return sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
}

int16_t sfm_sf06_update_concentration(uint16_t volume_fraction) {
    int16_t error = sfm_sf06_update_concentration_set(volume_fraction);
    if (error) {
        return error;
    }
    return sfm_sf06_update_concentration_activate();
}

int16_t sfm_sf06_stop_continuous_measurement(void) {
    uint8_t buffer[2];
    uint16_t offset = 0;
    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x3FF9);

    return sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
}

int16_t sfm_sf06_configure_averaging(uint16_t average_window) {
    uint8_t buffer[5];
    uint16_t offset = 0;
    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x366A);

    offset = sensirion_i2c_add_uint16_t_to_buffer(&buffer[0], offset,
                                                  average_window);

    return sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
}

int16_t sfm_sf06_read_scale_offset_unit(command_code_t command_code,
                                        int16_t* flow_scale_factor,
                                        int16_t* flow_offset,
                                        uint16_t* flow_unit) {
    int16_t error;
    uint8_t buffer[9];
    uint16_t offset = 0;
    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x3661);

    offset =
        sensirion_i2c_add_uint16_t_to_buffer(&buffer[0], offset, command_code);

    error = sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
    if (error) {
        return error;
    }

    sensirion_i2c_hal_sleep_usec(0);

    error =
        sensirion_i2c_read_data_inplace(SFM_SF06_I2C_ADDRESS, &buffer[0], 6);
    if (error) {
        return error;
    }
    *flow_scale_factor = sensirion_common_bytes_to_int16_t(&buffer[0]);
    *flow_offset = sensirion_common_bytes_to_int16_t(&buffer[2]);
    *flow_unit = sensirion_common_bytes_to_uint16_t(&buffer[4]);
    return NO_ERROR;
}

int16_t sfm_sf06_enter_sleep(void) {
    uint8_t buffer[2];
    uint16_t offset = 0;
    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x3677);

    return sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
}

int16_t sfm_sf06_exit_sleep(void) {
    uint8_t buffer[2];
    uint16_t offset = 0;
    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0x00);

    return sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
}

int16_t sfm_sf06_read_product_identifier(uint32_t* product_identifier,
                                         uint8_t* serial_number,
                                         uint8_t serial_number_size) {
    int16_t error;
    uint8_t buffer[18];
    uint16_t offset = 0;
    offset = sensirion_i2c_add_command_to_buffer(&buffer[0], offset, 0xE102);

    error = sensirion_i2c_write_data(SFM_SF06_I2C_ADDRESS, &buffer[0], offset);
    if (error) {
        return error;
    }

    sensirion_i2c_hal_sleep_usec(0);

    error =
        sensirion_i2c_read_data_inplace(SFM_SF06_I2C_ADDRESS, &buffer[0], 12);
    if (error) {
        return error;
    }
    *product_identifier = sensirion_common_bytes_to_uint32_t(&buffer[0]);
    sensirion_common_copy_bytes(&buffer[4], serial_number, serial_number_size);
    return NO_ERROR;
}
